### ISSUE TITLE
Installation on macOS

### ISSUE THREAD

**Issue by roelvangils** [esimov/caire#10]
I'm new to Go. I have this version installed:

```
go version go1.9.3 darwin/amd64
```

I followed the basic installation instructions from the README:

```
$ go get github.com/esimov/caire/cmd/caire
$ go install
```

Afte running the `go get` command, I end up with a `go` folder in my filesystem's root. I'm not sure where I should execute `go install` or what should happen next. Should I simply put the `caire` executable in a specific folder to make it work?

Thanks for your help.
Roel

**Comment by esimov** [comment]
Follow the instruction from https://golang.org/doc/install. 
First, install Go, set your `GOPATH`, and make sure `$GOPATH/bin` is on your `PATH`.
```
$ export GOPATH="$HOME/go"
$ export PATH="$PATH:$GOPATH/bin"
```
