### ISSUE TITLE
Extremely slow

### ISSUE THREAD

**Issue by rybi** [esimov/caire#11]
I tried to rescale an image of the dimensions 2100 x 1300, scaling it down by 20 percent.
It took fifty minutes:

```
caire -in s.jpg -out out.jpg -perc=1 -width 20 -height 20
Processing... |
Rescaled in: 2952.92s
Saved as: out.jpg 
```
Working on a recent macbook, go version go1.7.1 darwin/amd64
Am I doing something wrong?

**Comment by nesevis** [comment]
I'm on a 3.4ghz i5 (2017 iMac), and a 1500x1000 image compressed to 1000x1000 took 4 minutes.

**Comment by esimov** [comment]
Normally for an 2100x1300 image the downscale to 20% shouldn't take so much time, however the process is resource dependent.

**Comment by rybi** [comment]
4 Minutes is better. However, imagemagick with liblqr needs just a few seconds for the same task.

**Comment by esimov** [comment]
It could be, I haven't tried it. If it's faster and better for you, then use that.
