### ISSUE TITLE
Enhancement: Proportional scaling first

### ISSUE THREAD

**Issue by Scott-MacD** [esimov/caire#17]
When generating an image at, for example, half "resolution", this tool creates undesirable effects as it tries to remove half the image data while keeping everything at it's current resolution, resulting in rather mangled output. The solution to this is to first resize the image using a traditional scaling method without applying any cropping, then passing the data to this tool to apply the cropping to the image.

It would be nice to see a flag, that when set, would automatically pre-scale an image before applying this algorithm to it.

eg:
Given an image of dimensions `2048x1536` if I supply a command similar to the following:
`caire -in image.jpg -out thumb.jpg -width=1024 -height=500 -scale=1`
it would be nice to see the tool first resize the image to 1024x768, then utilize it's existing algorithms to remove the final 268 pixels instead of its current implementation on trying to keep everything the same scale and having to remove much more data.

I don't know if keeping the original resolution image is beneficial for calculating better seems however.

**Comment by esimov** [comment]
I enhanced the existing features with the requested one. Please check the documentation for how to use it and let me know if it's working for you.
