### ISSUE TITLE
console color not reset after finish

### ISSUE THREAD

**Issue by beenotung** [esimov/caire#23]
after I run the resize successfully, it print out:
```
Rescaled in: 17.47s
Saved as: out.jpg 
```
where `17.47s` and `out.jpg` are in green color, other are same as console default color.
But the reset of the console (username:folder$ ) are still in green color.

**Comment by esimov** [comment]
Can you show me an image?

**Comment by esimov** [comment]
Since i do not received an answer i will close this issue.

**Comment by beenotung** [comment]
![1](https://user-images.githubusercontent.com/6007292/36341819-f9ed424a-142e-11e8-93f7-d9326047581e.png)
@esimov sorry for late reply. Here attached the screenshot of the problem.
