### ISSUE TITLE
wrong resize dimension

### ISSUE THREAD

**Issue by beenotung** [esimov/caire#24]
my input image is of size 204x383 (portrait).

Whenever I run
```
caire -in in.jpg -out out.jpg -width=$((204*3/2)) -height=$((383*3/2))
```
or
```
caire -in in.jpg -out out.jpg -width=$((383*3/2)) -height=$((204*3/2))
``` 
The output image is in landscape (though it doesn't looks the same).

| Input Size | Resize Size | Actual Output Size |
|---|---|---|
| 204x383 | 306x574 | 306x192 |
| 204x383 | 574x306 | 574x306 |

**Comment by esimov** [comment]
I tried to reproduce the issue without success, but i think it has to do with this https://github.com/esimov/caire/issues/22, which has already been fixed. I will close this issue, but if you can still reproduce it, please reopen it.
