### ISSUE TITLE
enlarge by percentage is not supported

### ISSUE THREAD

**Issue by beenotung** [esimov/caire#25]
```
$ caire -in in.png -out out.jpg -perc=1 -width=150 -height=150 -debug=false
Processing... -
Error rescaling image: in.png. Reason: The generated image size should be less than original image size.
```

while specifying the enlargement size also have other problems as mentioned in https://github.com/esimov/caire/issues/24

**Comment by esimov** [comment]
In case you use the percentage flag you have to specify to what percentage you want to rescale the image. The example below will rescale the image width and height by 20%. Please consult the readme for this matter.

`caire -in in.jpg -out out.jpg -perc=1 -width=20 -height=20`

In either case percentage value should not exceed 100, because this means it will decrease the image by 100%.

**Comment by Scott-MacD** [comment]
Perhaps changing the percentage parameters to be the inverse of what they are would be more intuitive? I definitely made this mistake a couple times before I realized what I was doing wrong. To me this reads "scale an image to 20%", meaning, 20% of the original image size, not scaled down by 20%. In the current implementation is it even possible to scale up using percentages? How would you do so? 

Does the command except decimals?
`caire -in in.jpg -out out.jpg -perc=1 -width=0.8 -height=0.8`

Do we use negative numbers?
`caire -in in.jpg -out out.jpg -perc=1 -width=-20 -height=-20`


Using this inverted semantics seems to be a little more intuitive and easier to reason about:

Resize to aprox one third the original size:
`caire -in in.jpg -out out.jpg -perc=1 -width=30 -height=30`

Resize to double the original size:
`caire -in in.jpg -out out.jpg -perc=1 -width=200 -height=200`

**Comment by esimov** [comment]
@Scott-MacD i admit that the explanation creates some confusion. I will update the description pretty soon. 
> In the current implementation is it even possible to scale up using percentages? 

At the moment the percentage flag is support only for scale down operation.

>Does the command accept decimals? 

No, it does not. I don't see the reason to accept decimals, considering that we operate on pixel size.
