### ISSUE TITLE
Stuck in Processing state

### ISSUE THREAD

**Issue by avolochenko** [esimov/caire#28]
Trying to run it on a MacbookPro (13" 2016 3.3ghz i7), but cant get anywhere past Processing message.

I've installed caire via homebrew, my sample image is the one used in the repo:
https://user-images.githubusercontent.com/883386/35498083-83d6015e-04d5-11e8-936a-883e17b76f9d.jpg

Command:
caire -in input.jpg -out output.jpg -width=300 -height=200
Processing... /

Any ideas?
I've tried the same on an Ubuntu docker container with go 1.10 and same result.

**Comment by avolochenko** [comment]
I guess it takes a bit to process on the MBP, finished after 380s. Can close this issue.

**Comment by alexellis** [comment]
I'm also getting the same issue, I have a relatively small-sized desktop wallpaper and am getting no feedback but it's taking a super long time to make square.

**Comment by alexellis** [comment]
240KB and 1500 × 657 pixels

**Comment by esimov** [comment]
@alexellis what command did you used? To speed up the process first you can scale it down by using the `-scale` option (please refer to the documentation on how to use this option and get a better understanding of how this works), then `-square` option will make it square. Normally this will give a huge speedup. Can you attach the picture to test on my environment?
