### ISSUE TITLE
Processing does not finish

### ISSUE THREAD

**Issue by Kreshnik** [esimov/caire#30]
I was trying to resize an `png` image of the dimension `1200 × 750` to `120 x 120`. However, the terminal output stuck at `Processing... -` for minutes.

**Comment by frnwtr** [comment]
+1

**Comment by nacanori** [comment]
Ditto. I am using macOs Sierra.

**Comment by esimov** [comment]
Please use the `-scale` option in case you wish to reduce the image size considerably. Using this option first the image is scale down, then the seam carving algorithm is applied. Check the documentation for more details.

**Comment by nacanori** [comment]
Great! I have solved the problem.

**Comment by esimov** [comment]
Then i will close this issue.
