### ISSUE TITLE
Wrap CAIRE up into an app

### ISSUE THREAD

**Issue by ajayns** [esimov/caire#31]
Hey!
I feel it'd be great having this as tool as a Web App for general public to make use of. Would you be interested in building a backend over this so that a Web App (which I could build) could use it as an API. 

Anyone interested in such a project feel free start a discussion cause I see potential in this!

-ajayns

**Comment by esimov** [comment]
Hey, thanks. Right now i'm not planning to make an APP form this tool, but to expose the result and the params via a REST api would'n require to much effort, so i might consider to implement in feature version.

**Comment by ajayns** [comment]
Yes! A rest.api would be great! Do let me know about the progress! @esimov

**Comment by LazyBun** [comment]
@ajayns I've recently created a webapp which uses Caire. Check it out [here](https://budziol.piszkod.pl/). If you need some additional features then please let me know - I'll gladly add them.

**Comment by ajayns** [comment]
@LazyBun That's great, it looks cool! Did you wrap up this into a REST API for your app? Is that available as a deployment?

**Comment by LazyBun** [comment]
@ajayns It's a serverless application (AWS Lambda) which runs Caire with given parameters for given image. You could deploy it - after all the code is available [here](https://gitlab.com/budziol/). If you want to and need instructions, please let me know.
