### ISSUE TITLE
Homebrew Installation is Out of Date

### ISSUE THREAD

**Issue by quicklikerabbit** [esimov/caire#33]
Trying to take the library for a spin, but it seems like the Homebrew installation is out of date. After installing and running `caire --help` I get the following output: 
```
Usage of caire:
  -blur int
    	Blur radius (default 1)
  -debug
    	Use debugger
  -height int
    	New height
  -in string
    	Source
  -out string
    	Destination
  -perc
    	Reduce image by percentage
  -sobel int
    	Sobel filter threshold (default 10)
  -square
    	Reduce image to square dimensions
  -width int
    	New width
```

Some notable flags missing are `-scale` and `-face`. I've tried to use both of these as my images never seem to finish processing. 

I tried the alternative installation method, but when I run `go get -u -f github.com/esimov/caire/cmd/caire` I get the following error (could open a separate issue for this if needed):
```
# gocv.io/x/gocv
imgproc.cpp:27:26: error: expected '(' for function-style cast or type construction
imgproc.cpp:30:19: error: expected '(' for function-style cast or type construction
imgproc.cpp:133:28: error: expected '(' for function-style cast or type construction
```

Anyone else experiencing something similar?

**Comment by esimov** [comment]
On the initial release the face detection feature was missing. Lately i extended the library to support face detection using gocv.io. But because gocv requires a lot of dependencies and it's installation is a bit cumbersome, i opted to not include into the binary release. And because in the end Homebrew installation is based on the binary file, this is the reason why the new options are not available. 

I'm working on my custom face detection library and soon i will replace gocv and will update homebrew with the new release.

**Comment by esimov** [comment]
@quicklikerabbit  i have updated the app to support my own face detection library, so no more 3rd party modules and libraries are used. I also updated the homebrew package. Please check it and let me know if it's working.

**Comment by quicklikerabbit** [comment]
Installation worked perfectly, however, when I use the `-face` flag now I get the following error message: `Please provide an xml face classifier!`

**Comment by esimov** [comment]
You need to provide the face classifier file which can be found on the data folder.

**Comment by quicklikerabbit** [comment]
Awesome, thank you. One last question, how do I 'provide' the classifier to the CLI?

**Comment by esimov** [comment]
You need to use the `-cc` flag. Here is an example: 
`$ caire -in source.jpg -out out.jpg -perc=1 -width=20 -height=20 -face=1 -cc=data/facefinder`
