### ISSUE TITLE
Implement own face detection library to remove opencv dependency

### ISSUE THREAD

**Issue by wburningham** [esimov/caire#35]
In your readme you said
>i'm planning to implement my own face detection library to minimize the dependency tree

I wanted to create this ticket so I could watch it and get notified when this is done. I'd love to be able to just install th binary and not have to use homebrew or install any dependencies.

Thanks

**Comment by esimov** [comment]
I have already finished the library implementation, i just need to replace the face detection code section with my own. Meantime you can check it here: https://github.com/esimov/pigo/

**Comment by esimov** [comment]
@wburningham just replaced `gocv` with `pigo` for the face detection functionality. Now you should use `caire` without any third party library or module.

**Comment by xhappy** [comment]
How to specify the 'pigo' package when run caire command?
