### ISSUE TITLE
how to run carie

### ISSUE THREAD

**Issue by shravanvj** [esimov/caire#37]
How do I run this tool?
how do you upload an image from a source

**Comment by esimov** [comment]
It's explained in the readme file. Use the CLI tool.

**Comment by shravanvj** [comment]
I followed it 
I've set the go path and then I used go get -u -f github.com/esimov/caire/cmd/caire
but when I run the Go Install command
It says can't load packages, no go files found

**Comment by esimov** [comment]
Select the folder you have just created by installing the package and run the `go install` command from there. Si in your case `cd $GOPATH/src/github.com/esimov/caire/cmd/caire`

**Comment by shravanvj** [comment]
I tried doing that, but it still says no go files found

**Comment by esimov** [comment]
Have you reached `github.com/esimov/caire/cmd/caire` ?

**Comment by shravanvj** [comment]
No, I cannot reach it

**Comment by shravanvj** [comment]
![screenshot 3](https://user-images.githubusercontent.com/39951454/41526988-6bb78088-7303-11e8-9d87-f3d90cc44ed5.png)
 this is what's happening

**Comment by esimov** [comment]
This means it's working. Follow the readme file, all the details are there.

**Comment by shravanvj** [comment]
In the readme file , it is given under the usage tab $ caire -in input.jpg -out output.jpg
when I run this on cli it throws invalid command

**Comment by esimov** [comment]
And have you tried to run `go install` from the `cmd/caire` folder? This will install the binary file under `$GOPATH/bin` folder. Can you check if it's there?

**Comment by shravanvj** [comment]
Yes, there is an exe file named caire

**Comment by esimov** [comment]
This meas the `$GOPATH/bin`  folder is not exported. You have to run or add these two lines into windows environment variables. 
```
$ export GOPATH="$HOME/go"
$ export PATH="$PATH:$GOPATH/bin"
```
Follow this article for guidance: https://golang.org/doc/install

**Comment by esimov** [comment]
Yes, but you have to do in the Windows way. Just follow along the above article and it will help.

**Comment by shravanvj** [comment]
I did the following, but still facing the same issue

**Comment by shravanvj** [comment]
I reinstalled go and performed as instructed in the document, but now it's completely different  
![screenshot 5](https://user-images.githubusercontent.com/39951454/41529984-5f286928-730c-11e8-8218-bf69b96eedeb.png)

**Comment by esimov** [comment]
It's strange. Which Go version have you installed?

**Comment by shravanvj** [comment]
go 1.10.3

**Comment by shravanvj** [comment]
so should I set the goroot to bin as well?

**Comment by shravanvj** [comment]
Fixed it, but still, the exe file opens and closes instantly upon a click

**Comment by esimov** [comment]
It opens and closes instantly because you have to provide at least an input and output file, so you should run it from the terminal.

**Comment by shravanvj** [comment]
How do I do that?

**Comment by shravanvj** [comment]
when I run it on terminal this is what I g
![screenshot 8](https://user-images.githubusercontent.com/39951454/41533109-3d061754-7317-11e8-8ce5-f0e4ebe968f9.png)
et

**Comment by esimov** [comment]
It's pretty self-explanatory: you need to provide and input and an output file, exactly as it's stated in the documentation. Also why you are not using the executable file?

**Comment by shravanvj** [comment]
Where can I find the executable file, I tried providing an i/o file , it just throws an error

**Comment by shravanvj** [comment]
The exe file is not working, It closes upon a click

**Comment by shravanvj** [comment]
Where should be the input file must be present, how do you call a file which is in the desktop

**Comment by shravanvj** [comment]
![screenshot 9](https://user-images.githubusercontent.com/39951454/41578089-1721591c-73ae-11e8-903b-6ac619cc76c1.png)
 I've been trying to upload an image from c:\go\bin

**Comment by shravanvj** [comment]
Please help me

**Comment by shravanvj** [comment]
No its not

**Comment by shravanvj** [comment]
I have an image in the folder go/bin so I gave the command:
caire -in C:\Go\bin\vader.jpg -out ./out.jpg -perc=1 -width=20 -height=20 -debug=true
it says cannot find the file

**Comment by esimov** [comment]
Can you list the the current directory structure from where you are trying to run the command?

**Comment by esimov** [comment]
Checking your Go environment i see that it is not configured correctly. 

Normally `$GOPATH` should be  something like `GOPATH="C:\Path\ToYourLocal\GoProjects\Directory"`. Currently `GOPATH` is set to `C:\Go\bin` which is not correct. It should be like `C:\Users\Shravan\Go`. 

Inside this folder you should create a `src` folder, then once you `go get` the `caire` project you will have a new folder defined as `github.com\esimov\caire`. So the final path should be: `C:\Users\Shravan\Go\src\github.com\esimov\caire`. 

If you setup and configure Go correctly and if you are not using OneDrive (because there is an issue running Go on Windows10 using OneDrive: https://github.com/golang/go/issues/22579) then everything should work. Also please list your directory content. Are you sure the image file exists? Another remark: do not mess up the linux and windows directory separators.

**Comment by shravanvj** [comment]
My go path is set to C:\Users\Shravan\Go and I have the project in src of go

**Comment by esimov** [comment]
Have you managed to run the app? I haven't received any feedback and i'm about to close this issue.
