### ISSUE TITLE
how to use Pigo face detector when run caire command

### ISSUE THREAD

**Issue by xhappy** [esimov/caire#38]
Hi
since caire provide the flag '-face', but when I specified this flag, caire will report a error that is 'please provide a face classifier file'. I know Pigo is face detector which can be used here, but I don't know how to use it. Could you please help me ? Thanks in advance.

**Comment by esimov** [comment]
I have updated the README file to explain how to use the face detection functionality prior rescaling. You have to use the `-face=1` flag and also you need to provide the face clasification file found on `data` folder.

Here is a sample code how to use it:

`$ caire -in input.jpg -out output.jpg -face=1 -cc="data/facefinder" -perc=1 -width=20`

Hope that helps.
