### ISSUE TITLE
Leaky ASCII colours

### ISSUE THREAD

**Issue by alexellis** [esimov/caire#42]
Hi there, I resized an image and the yellow/green highlight got left on. I guess this may be a bug in terminator code? Is an expression missing?

<img width="934" alt="screen shot 2018-08-13 at 4 35 02 pm" src="https://user-images.githubusercontent.com/6358735/44041953-f262df12-9f16-11e8-956e-03a6212e52a4.png">

Thanks,

Alex

**Comment by alexellis** [comment]
<img width="901" alt="screen shot 2018-08-13 at 4 36 21 pm" src="https://user-images.githubusercontent.com/6358735/44041990-0e0c4de8-9f17-11e8-8d19-fec46f566ea0.png">

Also happened with another transform ^

Thanks

**Comment by alexellis** [comment]
This was with go get. Thanks for looking.

**Comment by esimov** [comment]
Also it's strange, because the processing indicator is broken. The terminal color issue is due to this. It happens each time?

**Comment by esimov** [comment]
@alexellis closing the issue since i haven't received any feedback from you. If you are still facing this issue you can reopen it.
