### ISSUE TITLE
very very slow

### ISSUE THREAD

**Issue by lxzan** [esimov/caire#45]
MacBook Pro 1014 mid

**Comment by esimov** [comment]
Please be more specific. What is the image resolution and the completion time.

**Comment by lxzan** [comment]
https://user-images.githubusercontent.com/883386/37569642-0c5f49e8-2aee-11e8-8ac1-d096c0387ca0.jpg, the demo image you provide, ./caire -in 1.jpg -out 2.jpg -width=400 -height=400, cost 37s, It's unbearable to use it on product environment. Would it be much more fast by using nvidia GPU ?

**Comment by esimov** [comment]
Please be aware that there are multiple factors which determines the performance of the application: 
1. The image resolution
2. If face detection option has been used (this will increase the execution time)
3. The magnitude of the resize

The application is not using the GPU.
