### ISSUE TITLE
[minor] Image example labelled "scotland" is not Scotland.

### ISSUE THREAD

**Issue by SafariMonkey** [esimov/caire#5]
FYI, the image labeled "scotland" is in fact Gásadalur in the Faroe Islands, which is easily corroborated by a google image search. It's a beautiful place which I have been to many times, so I'd appreciate if the caption was fixed.

This project does look very interesting! I'd know that view from anywhere, though, so I thought I'd let you know.

**Comment by esimov** [comment]
Thanks for notifying, modified.
