### ISSUE TITLE
Using -square seems to take forever

### ISSUE THREAD

**Issue by mosic** [esimov/caire#55]
I used caire with a couple of images, and aside from the girl example in the README, I haven't gotten it to actually provide an output with any of the images I tried, even after 10-15mins. I have tried using different flags to make it faster, but it seems to be stuck processing forever.

Here's an example to reproduce my issue:

``` sh
wget -O input.jpg "https://unsplash.com/photos/CaDoHQ3fB8w/download?force=true"
caire -in input.jpg -out output.jpg -face=false -scale -square -width=500 -height=500 -blur=0
```

Any suggestions?

**Comment by esimov** [comment]
Thanks for letting me know this issue. It was a missing conditional check in the image processing part. This issue should have been fixed now. Please test it and let me know if it's working on your end.

Below is the end result obtained running the command you have used.

![output](https://user-images.githubusercontent.com/883386/69042527-0050f100-09fa-11ea-87e7-8974a498f0dd.jpg)

**Comment by mosic** [comment]
That was fast! Yeah, the issue seems to be fixed on my side as well. Thanks for looking into it.

I tried it with another image and got a weird result though, maybe it should be a separate issue:

``` sh
wget -O input.jpg "https://unsplash.com/photos/TjOH0ymV7oU/download?force=true"
caire -in input.jpg -out output.jpg -face=false -scale -square -width=500 -height=500 -blur=0
```

This is the original:

![input](https://user-images.githubusercontent.com/1229422/69053282-fa124300-0a00-11ea-878c-b8bf71920d26.jpg)

And this is the output:

![output](https://user-images.githubusercontent.com/1229422/69053288-01395100-0a01-11ea-8bda-b566450a086a.jpg)

**Comment by esimov** [comment]
This is not related to some bug or issue in the algorithm, since it has a "dense" background the nature of this image does not permits to generate a good output.

**Comment by mosic** [comment]
Ah, fair enough. :+1:
