### ISSUE TITLE
Option to hide seams on output

### ISSUE THREAD

**Issue by DreamingInBinary** [esimov/caire#6]
Great work on this, I'm having fun just messing around with it.

Forgive me if this is obvious - but is there a way to hide the seams on the output file? Each result I have includes the red seams on the image.

Thanks!

**Comment by esimov** [comment]
As it's described in the readme file, you have the option to debug the process, by using the `--debug=1` flag. The red seams are appearing because probably you have forgotten to disable the debug flag.

**Comment by DreamingInBinary** [comment]
Thanks for the tip @esimov 👍  I did read the whole readme, but it doesn't say anywhere what the debug flag actually does, it just says that you can toggle it 😄 

Keep up the great work, I had a great time playing around with it yesterday!

**Comment by esimov** [comment]
Thanks @DreamingInBinary, i'm really glad that you like it.
