### ISSUE TITLE
Support masks

### ISSUE THREAD

**Issue by VelocityRa** [esimov/caire#68]
### Is your feature request related to a problem? Please describe.
For people/animal inputs (or anything whose proportions shouldn't change) this project very often resizes those instead of other things like the environment ie. a background landscape.

It does not seem usable for me for anything other than landscapes or abstract images.
I use it like so:
```
caire -in input.jpg -out output.jpg -face=1 -width=400 -height=300
```

### Describe the solution you'd like
Masking support. An optional protective binary mask image file, like this from https://github.com/andrewdcampbell/seam-carving.
> `-mask`: (Optional) The path to the protective mask. The mask should be binary and have the same size as the input image. White areas represent regions where no seams should be carved (e.g. faces).

### Describe alternatives you've considered
Using the above project. But there are no releases/binaries, it's not as easy to use.

**Comment by esimov** [comment]
The requested feature has been implemented. Please test it out and let me know your thoughts. Soon a new release will follow.

**Comment by VelocityRa** [comment]
I have no need for this anymore, but I trust it works :) might as well close.
