### ISSUE TITLE
error while loading shared libraries: libEGL.so.1 (installed caire using snap)

### ISSUE THREAD

**Issue by NarenZen** [esimov/caire#73]
Installed caire using `sudo snap install caire`.

Then I gave caire command. This is the error I'm getting

`/snap/caire/128/bin/caire: error while loading shared libraries: libEGL.so.1: cannot open shared object file: No such file or directory`

**Comment by esimov** [comment]
Thanks for letting me know. I will investigate and come back to you.

**Comment by esimov** [comment]
Can you tell me on what operating system wanted to install it? I've tried using Ubuntu 16.04 and it's working. Did you have it already installed?

**Comment by NarenZen** [comment]
Ubuntu 20.04.3 LTS

**Comment by NarenZen** [comment]
Also tried with Ubuntu 18 as well. Same error

**Comment by esimov** [comment]
I will try to check with these releases.

**Comment by dmirecki** [comment]
Hi, is there any update in the topic?

**Comment by esimov** [comment]
The error should be fixed now.

**Comment by dmirecki** [comment]
Now it works, thank you!
