### ISSUE TITLE
Is a tutorial available

### ISSUE THREAD

**Issue by esobczak1970** [esimov/caire#80]
### Is your feature request related to a problem? Please describe.

Seems like an amazing library but I can't find any tutorials and wondered if there are any.

### Describe the solution you'd like

Even a brief tutorial with a few examples would be great.

### Describe alternatives you've considered

I will inquire of more experienced go programmers than myself but would love to use this tech.

### Additional context

Thanks I've searched web a bit and for as many stars as this repository I'm amazed there aren't more demo's of it's use.

**Comment by esimov** [comment]
Thank you for the feedback and probably you are right, that I should create a tutorial about how someone should use this library. So I'm considering writing an article or tutorial in the upcoming future. I will open this ticket and will keep you updated.

**Comment by esimov** [comment]
Finally I found some time to publish a tutorial about the usage of the library. You can check it here: 
https://medium.com/@esimov/how-to-use-caire-the-content-aware-image-resize-library-e4b61e35e202
