### ISSUE TITLE
Preserve Jpeg color profile

### ISSUE THREAD

**Issue by purplefish32** [esimov/caire#82]
When I try to use the lib on a jpeg input file to a jpeg output format the colour profile is not preserved resulting in a shifting in the output colours

The solution would possibly be to retain the input colour profile or being able to assign a desired colour profile to the output

**Comment by esimov** [comment]
What do you mean by color space is not preserved? Could you explain? Even better would be if you could attach the source image and the resulted output.

**Comment by purplefish32** [comment]
The first one (in) is in Adobe RGB (1998) colour space, the second one (out) becomes sRGB ICE61966-2.1

Notice the colours are also less vibrant.

<img width="592" alt="Screenshot 2022-09-22 at 14 55 25" src="https://user-images.githubusercontent.com/479917/191753565-6cbe7503-f228-406f-9c85-e8447b0e7eae.png">

This is the command I am using : 

> caire -in beach.jpg -width 1969 -out beach2.jpg -debug=1

So here are the two images : 

![beach](https://user-images.githubusercontent.com/479917/191753520-9e007659-cc93-4dd7-84e5-173c5c3d2eb2.jpg)
![beach (1)](https://user-images.githubusercontent.com/479917/191753527-c6947f01-32af-48a9-8690-c338b25dace9.jpg)

**Comment by purplefish32** [comment]
Once uploaded to Github, both the in and out image seem to be more or less the same, I think the Github image preview is reincoding them or something,

You can try a download one and use caire on it to reproduce the issue

**Comment by purplefish32** [comment]
And sorry it is the colour profile that changes, not the colour space

**Comment by esimov** [comment]
I've done a little research, but unfortunately the image package does not preserve the color profile of the original image on encoding. There are other tools like `exiftool` where you can modify the color profile of an image or `libvips` which actually has a go [binding](https://github.com/davidbyttow/govips) also, but I'm not planning of integrating into Caire.

**Comment by purplefish32** [comment]
OK, thank you for taking the time to investigate
