### ISSUE TITLE
Unable to run on  ubuntu

### ISSUE THREAD

**Issue by kartikwar** [esimov/caire#83]
Hello I have installed the caire as a snap function. But when I try to run it I keep getting this error

**common: ERROR: failed to add default include path /usr/share/X11/xkb
xkbcommon: ERROR: failed to add default include path /usr/share/X11/xkb**

Can you please help me in fixing this? Thanks in advance.

**Comment by esimov** [comment]
Can you share the whole error you are receiving? I assume this is a Snap related issue.

**Comment by esimov** [comment]
This is related to issue #79, so I'm closing this ticket.
