### ISSUE TITLE
"Preview not available" dialog for horizontal + vertical resize should not take priority over the preview flag

### ISSUE THREAD

**Issue by Nathansbud** [esimov/caire#99]
### API related bug

When using the CLI interface, setting `preview -false` does _not_ hide the popup that alerts that no preview can be displayed for resizes on multiple axes. This is unexpected behavior.

### Expected behavior

The current behavior (`preview -false` hiding the preview GUI) only applies to the case of resizing on a single axis. However, manually setting preview to be false should also hide the waiting preview pop-up, so as to not have to manually exit it afterwards.

**Comment by esimov** [comment]
I'm not sure if I understand exactly your issue. Could you send me the command line you are trying?

**Comment by Nathansbud** [comment]
`caire -in Image.jpg -out output.png -width 500 -height 500 -mask Keep.png -rmask Remove.png -preview false`; this is less a bug and more a note about it feeling inconsistent that the non-square resize dialog still pops up with `-preview false` flag on!

<img width="1030" alt="image" src="https://github.com/user-attachments/assets/1799bbce-4176-40b1-8b73-cd3dbb44e23e">

**Comment by esimov** [comment]
The reason why the dialog modal pops up is because you are not using correctly the `-preview` flag. It should be `-preview=false` or `-preview=0`.

**Comment by esimov** [comment]
I'm closing this issue.
